sudo: required

language: node_js
node_js:
  - "node"

script: jasmine

before_script:
    - chmod 0777 ./node_modules/.bin/jasmine
    - chmod 0777 ./Commands/ServerStatus
    - chmod 0777 ./Commands/VehiclePrices
    - chmod 0777 ./Core/CommandRouter
